<?php get_header(); ?>
<section class="hero"><div class="container hero-grid">
<div class="hero-copy"><p class="eyebrow eyebrow-line"><?php echo esc_html(fp_theme_copy('accueil', 'hero_label', 'Christophe Feret · Val-d’Oise')); ?></p><h1><?php echo esc_html(fp_theme_copy('accueil', 'hero_title', 'Peintre en bâtiment à Écouen.')); ?></h1><p class="hero-lead"><?php echo esc_html(fp_theme_copy('accueil', 'hero_lead', 'Peinture intérieure et extérieure, revêtements de sols et murs.')); ?></p><p class="hero-description"><?php echo esc_html(fp_theme_copy('accueil', 'hero_description', 'Rafraîchir une pièce, rénover une façade ou changer un sol : Christophe Feret prépare les supports et réalise les finitions adaptées à votre projet.')); ?></p><p class="hero-description"><?php echo esc_html(fp_theme_copy('accueil', 'hero_visit', 'Une visite sur place pour évaluer les travaux avant le devis.')); ?></p><div class="hero-actions"><?php fp_theme_quote_button(); fp_theme_phone_link('', 'button button--text'); ?></div><div class="hero-footnote"><span class="small-mark" aria-hidden="true">F.</span><span>Une entreprise implantée à Écouen<br><strong>Créée en 2008</strong></span></div></div>
<figure class="hero-art hero-art--photo">
<div class="hero-photo-composition">
<img class="hero-photo" src="<?php echo esc_url(get_theme_file_uri('/assets/images/atelier-terracotta-1200.jpg')); ?>" srcset="<?php echo esc_url(get_theme_file_uri('/assets/images/atelier-terracotta-640.jpg')); ?> 640w, <?php echo esc_url(get_theme_file_uri('/assets/images/atelier-terracotta-1200.jpg')); ?> 1200w" sizes="(max-width: 700px) calc(100vw - 48px), (max-width: 1000px) 44vw, 560px" width="1200" height="1800" alt="Pinceau et rouleau aux teintes terracotta, devant un mur en cours de peinture." fetchpriority="high">
<div class="hero-palette"><img src="<?php echo esc_url(get_theme_file_uri('/assets/images/nuancier-360.jpg')); ?>" width="360" height="243" alt="Nuancier de tons naturels, du beige au rouge brique." decoding="async"></div>
</div>
<figcaption>Illustration des travaux de peinture.</figcaption>
</figure>
</div></section>
<?php if (fp_theme_services()) : ?>
<section class="section section-services"><div class="container"><div class="section-heading"><div><p class="eyebrow">Les prestations</p><h2><?php echo esc_html(fp_theme_copy('accueil', 'services_title', 'Quels travaux envisagez-vous ?')); ?></h2></div></div><div class="service-list"><?php fp_theme_service_rows(); ?></div><a class="text-link section-link" href="<?php echo esc_url(home_url('/prestations/')); ?>">Découvrir les prestations <?php echo fp_theme_arrow(); ?></a></div></section>
<?php endif; ?>
<?php if (fp_theme_has_projects()) : ?><section class="section projects-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Les réalisations</p><h2><?php echo esc_html(fp_theme_copy('accueil', 'projects_title', 'Quelques exemples de travaux')); ?></h2></div><a class="text-link" href="<?php echo esc_url(home_url('/realisations/')); ?>">Voir les réalisations <?php echo fp_theme_arrow(); ?></a></div><div class="project-grid"><?php fp_theme_project_cards(3); ?></div></div></section><?php endif; ?>
<section class="section company-section"><div class="container company-grid"><div class="company-emblem" aria-hidden="true"><span class="emblem-top">CHRISTOPHE FERET</span><span class="emblem-monogram">F.</span><span class="emblem-bottom">PEINTRE EN BÂTIMENT<br>ÉCOUEN</span></div><div class="company-copy"><p class="eyebrow"><?php echo esc_html(fp_theme_copy('accueil', 'company_label', 'Votre interlocuteur')); ?></p><h2><?php echo esc_html(fp_theme_copy('accueil', 'company_title', 'Christophe Feret')); ?></h2><p><?php echo esc_html(fp_theme_info('presentation', 'Christophe Feret est votre contact pour présenter vos travaux et convenir d’un rendez-vous sur place.')); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/entreprise/')); ?>">Découvrir l’entreprise <?php echo fp_theme_arrow(); ?></a></div></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Votre projet</p><h2><?php echo esc_html(fp_theme_copy('accueil', 'process_title', 'Un rendez-vous avant le devis')); ?></h2></div></div><ol class="process-list"><li><span class="step-number">01</span><h3><?php echo esc_html(fp_theme_copy('accueil', 'step_one_title', 'Prenez contact')); ?></h3><p><?php echo esc_html(fp_theme_copy('accueil', 'step_one_text', 'Appelez Christophe Feret ou laissez vos coordonnées pour convenir d’un rendez-vous.')); ?></p></li><li><span class="step-number">02</span><h3><?php echo esc_html(fp_theme_copy('accueil', 'step_two_title', 'Une visite sur place')); ?></h3><p><?php echo esc_html(fp_theme_copy('accueil', 'step_two_text', 'Christophe Feret se déplace pour examiner les supports et évaluer lui-même les travaux.')); ?></p></li><li><span class="step-number">03</span><h3><?php echo esc_html(fp_theme_copy('accueil', 'step_three_title', 'Un devis adapté au chantier')); ?></h3><p><?php echo esc_html(fp_theme_copy('accueil', 'step_three_text', 'Le devis est établi après cette visite, à partir des travaux convenus avec vous.')); ?></p></li></ol></div></section>
<section class="section locality-section"><div class="container locality-grid"><div><p class="eyebrow">Près de chez vous</p><h2><?php echo esc_html(fp_theme_copy('accueil', 'area_title', 'Votre peintre dans le Val-d’Oise et les environs.')); ?></h2><p><?php $area = fp_theme_info('confirmed_area'); echo esc_html($area ? $area : 'L’entreprise est implantée à Écouen. Pour un chantier dans une autre commune, indiquez sa localisation dans votre demande.'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/zone-intervention/')); ?>">Découvrir les secteurs d’intervention <?php echo fp_theme_arrow(); ?></a></div><div class="locality-card"><span class="locality-postcode">95440</span><span class="locality-name">Écouen</span><span class="locality-caption">Val-d’Oise · Implantation de l’entreprise</span><span class="locality-line" aria-hidden="true"></span></div></div></section>
<section class="section faq-section"><div class="container faq-grid"><div><p class="eyebrow">Avant de se lancer</p><h2><?php echo esc_html(fp_theme_copy('accueil', 'faq_title', 'Avant votre demande de rendez-vous.')); ?></h2></div><div class="faq-list"><details><summary><?php echo esc_html(fp_theme_copy('accueil', 'faq_one_question', 'Peut-on obtenir un devis en ligne ?')); ?></summary><p><?php echo esc_html(fp_theme_copy('accueil', 'faq_one_answer', 'Non. Un rendez-vous sur place est nécessaire pour que Christophe Feret évalue lui-même les travaux avant d’établir le devis.')); ?></p></details><details><summary><?php echo esc_html(fp_theme_copy('accueil', 'faq_two_question', 'Faut-il connaître la surface exacte ?')); ?></summary><p><?php echo esc_html(fp_theme_copy('accueil', 'faq_two_answer', 'Non. Une description des pièces ou des surfaces concernées suffit pour le premier contact.')); ?></p></details><details><summary><?php echo esc_html(fp_theme_copy('accueil', 'faq_three_question', 'Que détaille le devis ?')); ?></summary><p><?php echo esc_html(fp_theme_copy('accueil', 'faq_three_answer', 'Le devis décrit les travaux par pièce ou par surface : préparation des supports, revêtements et finitions, quantités et prix. Il précise aussi les travaux complémentaires et les conditions de règlement.')); ?></p></details><details><summary><?php echo esc_html(fp_theme_copy('accueil', 'faq_four_question', 'Puis-je envoyer des photos ?')); ?></summary><p><?php echo esc_html(fp_theme_copy('accueil', 'faq_four_answer', 'Le formulaire n’accepte pas de pièces jointes. Vous pourrez convenir avec Christophe Feret d’un moyen de lui envoyer vos photos.')); ?></p></details></div></div></section>
<?php fp_theme_contact_band(); get_footer(); ?>
