<?php get_header(); ?>
<section class="hero"><div class="container hero-grid">
<div class="hero-copy"><p class="eyebrow eyebrow-line">Christophe Feret · Val-d’Oise</p><h1>Peintre en bâtiment <em>à Écouen.</em></h1><p class="hero-lead">Un projet de peinture ?<br>Échangez avec Christophe Feret.</p><p class="hero-description">Peinture intérieure et extérieure, revêtements muraux et sols : présentez votre projet et sa commune.</p><div class="hero-actions"><?php fp_theme_quote_button(); fp_theme_phone_link('Appeler Christophe', 'button button--text'); ?></div><div class="hero-footnote"><span class="small-mark" aria-hidden="true">F.</span><span>Une entreprise implantée à Écouen<br><strong>Créée en 2008</strong></span></div></div>
<figure class="hero-art"><div class="art-frame" aria-hidden="true"><div class="art-wall"></div><div class="art-shadow"></div><div class="art-board art-board--clay"></div><div class="art-board art-board--cream"></div><div class="art-board art-board--green"></div><div class="art-card"><span class="art-card-color"></span><span class="art-card-rule"></span><span class="art-card-rule art-card-rule--short"></span></div><div class="art-swatch-row"><span></span><span></span><span></span></div><span class="art-index">01 - 04</span></div><figcaption><span>Matières & couleurs</span><span>Composition illustrative</span></figcaption></figure>
</div></section>
<?php if (fp_theme_services()) : ?>
<section class="section section-services"><div class="container"><div class="section-heading"><div><p class="eyebrow">Les prestations</p><h2>Quels travaux<br>envisagez-vous ?</h2></div><p>Une pièce à rafraîchir, des murs à reprendre ou un revêtement à changer : découvrez les prestations proposées.</p></div><div class="service-list"><?php fp_theme_service_rows(); ?></div><a class="text-link section-link" href="<?php echo esc_url(home_url('/prestations/')); ?>">Découvrir les prestations <?php echo fp_theme_arrow(); ?></a></div></section>
<?php endif; ?>
<?php if (fp_theme_has_projects()) : ?><section class="section projects-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Les réalisations</p><h2>Des chantiers, en images.</h2></div><a class="text-link" href="<?php echo esc_url(home_url('/realisations/')); ?>">Voir les réalisations <?php echo fp_theme_arrow(); ?></a></div><div class="project-grid"><?php fp_theme_project_cards(3); ?></div></div></section><?php endif; ?>
<section class="section company-section"><div class="container company-grid"><div class="company-emblem" aria-hidden="true"><span class="emblem-top">CHRISTOPHE FERET</span><span class="emblem-monogram">F.</span><span class="emblem-bottom">PEINTRE EN BÂTIMENT<br>ÉCOUEN</span></div><div class="company-copy"><p class="eyebrow">Votre interlocuteur</p><h2>Un nom.<br>Un contact direct.</h2><p class="large-copy">Derrière Feret Peinture,<br>Christophe Feret.</p><p><?php echo esc_html(fp_theme_info('presentation', 'L’entreprise est implantée à Écouen, dans le Val-d’Oise. Pour un premier échange, indiquez ce que vous souhaitez faire et où se situe votre chantier.')); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/entreprise/')); ?>">Découvrir l’entreprise <?php echo fp_theme_arrow(); ?></a></div></div></section>
<section class="section process-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Préparer votre demande</p><h2>Commençons simplement.</h2></div><p>Vous n’avez pas besoin d’avoir déjà toutes les réponses pour prendre contact.</p></div><ol class="process-list"><li><span class="step-number">01</span><h3>Décrivez votre projet</h3><p>Les pièces ou surfaces concernées, l’état actuel et les travaux que vous imaginez.</p></li><li><span class="step-number">02</span><h3>Précisez la commune</h3><p>La localisation du chantier permet de vérifier si votre projet peut être pris en charge.</p></li><li><span class="step-number">03</span><h3>Laissez un contact</h3><p>Un téléphone ou une adresse email pour poursuivre l’échange et préciser votre demande.</p></li></ol></div></section>
<section class="section locality-section"><div class="container locality-grid"><div><p class="eyebrow">L’implantation</p><h2>À Écouen.<br>Et votre projet, où est-il ?</h2><p><?php $area = fp_theme_info('confirmed_area'); echo esc_html($area ? 'Zone d’intervention confirmée : ' . $area . '.' : 'L’entreprise est implantée à Écouen. Pour un chantier dans une autre commune, indiquez sa localisation dans votre demande.'); ?></p><a class="text-link" href="<?php echo esc_url(home_url('/zone-intervention/')); ?>">Voir la zone d’intervention <?php echo fp_theme_arrow(); ?></a></div><div class="locality-card"><span class="locality-postcode">95440</span><span class="locality-name">Écouen</span><span class="locality-caption">Val-d’Oise · Implantation de l’entreprise</span><span class="locality-line" aria-hidden="true"></span></div></div></section>
<section class="section faq-section"><div class="container faq-grid"><div><p class="eyebrow">Avant de se lancer</p><h2>Quelques <br>réponses utiles.</h2></div><div class="faq-list"><details><summary>Que faut-il indiquer pour demander un devis ?</summary><p>Précisez la commune, le type de travaux et ce que vous souhaitez changer. Ajoutez un numéro de téléphone ou une adresse email pour permettre à Christophe de vous recontacter.</p></details><details><summary>Faut-il connaître la surface exacte ?</summary><p>Non. Une description des pièces ou des surfaces concernées suffit pour le premier contact. Les informations complémentaires pourront être précisées pendant l’échange.</p></details><details><summary>Puis-je envoyer des photos ?</summary><p>Le formulaire ne reçoit pas de pièces jointes. Si des photos sont utiles, leur transmission pourra être organisée lors du premier échange.</p></details><details><summary>Mon chantier est-il dans la zone d’intervention ?</summary><p>Indiquez la commune ou le code postal de votre chantier. Sa prise en charge sera à confirmer avec Christophe ; l’implantation à Écouen ne signifie pas que tous les projets de la région sont acceptés.</p></details></div></div></section>
<?php fp_theme_contact_band(); get_footer(); ?>
