<?php get_header(); while (have_posts()) : the_post(); $slug = get_post_field('post_name', get_the_ID()); ?>
<div class="container"><?php fp_theme_breadcrumb(); ?></div>
<?php if ($slug === 'devis') : ?>
<section class="page-intro quote-intro container"><h1>Demander un devis</h1><p class="intro-copy">Décrivez vos travaux et leur commune. Un téléphone ou un email suffit pour vous recontacter.</p><div class="quote-call"><?php fp_theme_phone_link('Vous préférez appeler Christophe ?', 'text-link'); ?></div></section>
<div class="container quote-layout"><section class="quote-form-wrap" aria-label="Formulaire de demande de devis"><?php if (function_exists('fp_render_quote_form')) { fp_render_quote_form(); } else { echo '<p>Le formulaire est en cours de préparation. Vous pouvez contacter Christophe par téléphone si ses coordonnées sont affichées.</p>'; } ?></section><aside class="quote-aside"><p class="eyebrow">Vous préférez appeler ?</p><h2>Christophe Feret</h2><?php fp_theme_phone_link('', 'phone-large'); fp_theme_email_link(); ?><p>Peintre en bâtiment<br>Implanté à Écouen, Val-d’Oise</p><div class="quote-help"><h3>Ce qui peut être utile</h3><ul><li>Les pièces ou surfaces concernées.</li><li>L’état actuel et le résultat souhaité.</li><li>La période envisagée, si vous en avez une.</li></ul><p>Les photos pourront être demandées lors du premier échange.</p></div></aside></div>
<?php elseif ($slug === 'entreprise') : ?>
<section class="page-intro container"><p class="eyebrow">L’entreprise</p><h1>Christophe Feret.<br><em>Peintre à Écouen.</em></h1><p class="intro-copy">Un interlocuteur identifié pour parler de vos travaux de peinture et de revêtements.</p></section>
<section class="container company-page-grid section section--topless"><div class="company-emblem" aria-hidden="true"><span class="emblem-top">CHRISTOPHE FERET</span><span class="emblem-monogram">F.</span><span class="emblem-bottom">PEINTRE EN BÂTIMENT<br>ÉCOUEN</span></div><div class="prose"><h2>Une entreprise locale</h2><p><?php echo esc_html(fp_theme_info('presentation', 'Christophe Feret est implanté à Écouen, dans le Val-d’Oise. L’entreprise exerce une activité de travaux de peinture.')); ?></p><h2>Une société créée en 2008</h2><p>La société CHRISTOPHE FERET a été créée le 27 janvier 2008.</p><h2>Le point de départ : votre projet</h2><p>Pour prendre contact, présentez les travaux envisagés et leur localisation. Les surfaces, l’état des supports et vos contraintes permettront ensuite de préciser la demande.</p><p>La nature exacte des travaux et les modalités du chantier sont à définir avec Christophe dans le devis.</p><a class="text-link" href="<?php echo esc_url(home_url('/prestations/')); ?>">Découvrir les prestations <?php echo fp_theme_arrow(); ?></a></div></section>
<?php fp_theme_contact_band(); ?>
<?php elseif ($slug === 'zone-intervention') : ?>
<section class="page-intro container"><p class="eyebrow">Votre commune</p><h1>Implanté à Écouen.<br><em>À propos de votre chantier.</em></h1></section>
<section class="container locality-grid section section--topless"><div class="prose"><p class="intro-copy">Le lieu du chantier est l’une des premières informations utiles pour préparer votre demande.</p><?php $area = fp_theme_info('confirmed_area'); if ($area) : ?><h2>La zone confirmée</h2><p><?php echo esc_html($area); ?></p><?php else : ?><h2>Où se situe votre projet ?</h2><p>L’entreprise est implantée à Écouen, dans le Val-d’Oise. Pour vérifier la prise en charge d’un chantier, indiquez la commune ou le code postal dans votre demande.</p><?php endif; ?><p>Chaque projet est à confirmer directement avec Christophe, selon la nature des travaux et leur localisation.</p><?php fp_theme_quote_button('Présenter mon chantier'); ?></div><div class="locality-card"><span class="locality-postcode">95440</span><span class="locality-name">Écouen</span><span class="locality-caption">Val-d’Oise · Île-de-France</span><span class="locality-line" aria-hidden="true"></span></div></section>
<?php elseif ($slug === 'merci') : ?>
<section class="container thank-you-page"><p class="eyebrow">Votre demande de devis</p><h1><?php echo function_exists('fp_quote_success_verified') && fp_quote_success_verified() ? 'Merci pour votre demande.' : 'Parlons de votre projet.'; ?></h1><?php if (function_exists('fp_quote_success_verified') && fp_quote_success_verified()) : ?><p class="intro-copy" data-form-success>Votre demande a été envoyée.</p><p>Vous avez une précision à ajouter à votre projet ? Vous pouvez aussi joindre Christophe par téléphone.</p><?php fp_theme_phone_link('', 'phone-large'); ?><?php else : ?><p class="intro-copy">Pour transmettre votre projet à Christophe, utilisez le formulaire de demande de devis.</p><?php fp_theme_quote_button(); ?><?php endif; ?><a class="text-link" href="<?php echo esc_url(home_url('/')); ?>">Retour à l’accueil <?php echo fp_theme_arrow(); ?></a></section>
<?php elseif (in_array($slug, array('mentions-legales', 'confidentialite'), true)) : ?>
<section class="page-intro container"><p class="eyebrow">Les informations du site</p><h1><?php the_title(); ?></h1></section><article class="container prose legal-content"><?php if (fp_theme_preview()) : ?><div class="validation-note"><strong>Document préparatoire — prévisualisation uniquement.</strong><p>Aliant et le responsable du site doivent compléter et valider les informations avant publication.</p></div><?php endif; ?><?php if (trim(get_the_content())) { the_content(); } elseif ($slug === 'mentions-legales') { get_template_part('inc/legal-draft'); } else { get_template_part('inc/privacy-draft'); } ?></article>
<?php else : ?>
<section class="page-intro container"><h1><?php the_title(); ?></h1></section><article class="container prose standard-page"><?php the_content(); ?></article>
<?php endif; endwhile; get_footer(); ?>
